//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.13 at 03:23:51 PM CET 
//


package usi.poc.business.impl.game.mapping;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the usi.poc.business.impl.game.mapping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Gamesession_QNAME = new QName("http://www.usi.com", "gamesession");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: usi.poc.business.impl.game.mapping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link Questiontype }
     * 
     */
    public Questiontype createQuestiontype() {
        return new Questiontype();
    }

    /**
     * Create an instance of {@link Sessiontype }
     * 
     */
    public Sessiontype createSessiontype() {
        return new Sessiontype();
    }

    /**
     * Create an instance of {@link Parametertype }
     * 
     */
    public Parametertype createParametertype() {
        return new Parametertype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sessiontype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.usi.com", name = "gamesession")
    public JAXBElement<Sessiontype> createGamesession(Sessiontype value) {
        return new JAXBElement<Sessiontype>(_Gamesession_QNAME, Sessiontype.class, null, value);
    }

}
