//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 06:10:50 PM CET 
//


package usi.poc.business.impl.game.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parametertype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="parametertype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="longpollingduration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nbusersthreshold" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="questiontimeframe" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nbquestions" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="flushusertable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="trackeduseridmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "parametertype", propOrder = {
    "longpollingduration",
    "nbusersthreshold",
    "questiontimeframe",
    "nbquestions",
    "flushusertable",
    "trackeduseridmail"
})
public class Parametertype {

    protected int longpollingduration;
    protected int nbusersthreshold;
    protected int questiontimeframe;
    protected int nbquestions;
    protected boolean flushusertable;
    @XmlElement(required = true)
    protected String trackeduseridmail;

    /**
     * Gets the value of the longpollingduration property.
     * 
     */
    public int getLongpollingduration() {
        return longpollingduration;
    }

    /**
     * Sets the value of the longpollingduration property.
     * 
     */
    public void setLongpollingduration(int value) {
        this.longpollingduration = value;
    }

    /**
     * Gets the value of the nbusersthreshold property.
     * 
     */
    public int getNbusersthreshold() {
        return nbusersthreshold;
    }

    /**
     * Sets the value of the nbusersthreshold property.
     * 
     */
    public void setNbusersthreshold(int value) {
        this.nbusersthreshold = value;
    }

    /**
     * Gets the value of the questiontimeframe property.
     * 
     */
    public int getQuestiontimeframe() {
        return questiontimeframe;
    }

    /**
     * Sets the value of the questiontimeframe property.
     * 
     */
    public void setQuestiontimeframe(int value) {
        this.questiontimeframe = value;
    }

    /**
     * Gets the value of the nbquestions property.
     * 
     */
    public int getNbquestions() {
        return nbquestions;
    }

    /**
     * Sets the value of the nbquestions property.
     * 
     */
    public void setNbquestions(int value) {
        this.nbquestions = value;
    }

    /**
     * Gets the value of the flushusertable property.
     * 
     */
    public boolean isFlushusertable() {
        return flushusertable;
    }

    /**
     * Sets the value of the flushusertable property.
     * 
     */
    public void setFlushusertable(boolean value) {
        this.flushusertable = value;
    }

    /**
     * Gets the value of the trackeduseridmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackeduseridmail() {
        return trackeduseridmail;
    }

    /**
     * Sets the value of the trackeduseridmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackeduseridmail(String value) {
        this.trackeduseridmail = value;
    }

}
