//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 06:10:50 PM CET 
//


package usi.poc.business.impl.game.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sessiontype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sessiontype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="questions" type="{http://www.usi.com}questiontype"/>
 *         &lt;element name="parameters" type="{http://www.usi.com}parametertype"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sessiontype", propOrder = {
    "questions",
    "parameters"
})
public class Sessiontype {

    @XmlElement(required = true)
    protected Questiontype questions;
    @XmlElement(required = true)
    protected Parametertype parameters;

    /**
     * Gets the value of the questions property.
     * 
     * @return
     *     possible object is
     *     {@link Questiontype }
     *     
     */
    public Questiontype getQuestions() {
        return questions;
    }

    /**
     * Sets the value of the questions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Questiontype }
     *     
     */
    public void setQuestions(Questiontype value) {
        this.questions = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parametertype }
     *     
     */
    public Parametertype getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parametertype }
     *     
     */
    public void setParameters(Parametertype value) {
        this.parameters = value;
    }

}
